-- Enable RLS on all TPO tables
ALTER TABLE "TpoUser" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TpoDate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TpoMessage" ENABLE ROW LEVEL SECURITY;

-- Enable RLS on existing tables
ALTER TABLE "MutualLike" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MutualTestUser" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BannedUser" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Shot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Vote" ENABLE ROW LEVEL SECURITY;
